#!/usr/bin/env ruby
# arbitrage
# 22-Sep-2013
#
# Usage:
#
$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), 'lib'))
require 'arbitrage'
# Arbitrage.new

x = Arbitrage.new
x.process_input
p x.n
p x.conversions
p x.profit?