#!/usr/bin/env ruby
# MadLibs
# usage:
#   ./madlibs
#
# on Windows run with: ruby madlibs [options]
$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), 'lib'))
require 'madlibs'
require 'madlib_game'
require 'fixtures'

MadLibs.new.play
